// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC13cy2oGN6lsqcedHqo_809LDluFk2tJo',
    appId: '1:368541298472:web:82bdd69848d4405e66aa1d',
    messagingSenderId: '368541298472',
    projectId: 'pega-pega-ufmt',
    authDomain: 'pega-pega-ufmt.firebaseapp.com',
    storageBucket: 'pega-pega-ufmt.appspot.com',
    measurementId: 'G-EKNMN4NN89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0kHQ01G6gaHPsLc3SqjM0y0psgMZpiTw',
    appId: '1:368541298472:android:e038fba95a359d2a66aa1d',
    messagingSenderId: '368541298472',
    projectId: 'pega-pega-ufmt',
    storageBucket: 'pega-pega-ufmt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3nqpoQ9jPvPiX7PTd8K_8ymcG1PuBZBI',
    appId: '1:368541298472:ios:eebbb1d89c45eb4f66aa1d',
    messagingSenderId: '368541298472',
    projectId: 'pega-pega-ufmt',
    storageBucket: 'pega-pega-ufmt.appspot.com',
    androidClientId: '368541298472-60rag3lntocqn7594c22tgr5c1pcmnh2.apps.googleusercontent.com',
    iosClientId: '368541298472-529chjmg3qf3emg1kub4usa9nnh83744.apps.googleusercontent.com',
    iosBundleId: 'com.example.pegaPega',
  );
}
