// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsqoC460UL3NivHxZtV3dgB-lLsO8WwqU',
    appId: '1:398887128767:web:bcfe399fefcd4d5e17000a',
    messagingSenderId: '398887128767',
    projectId: 'pet-app-aeb7b',
    authDomain: 'pet-app-aeb7b.firebaseapp.com',
    storageBucket: 'pet-app-aeb7b.appspot.com',
    measurementId: 'G-82D65LS4SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzOOCWA1xLzjA1qcqo8q3srBafbW6CoF8',
    appId: '1:398887128767:android:85c18697302c038317000a',
    messagingSenderId: '398887128767',
    projectId: 'pet-app-aeb7b',
    storageBucket: 'pet-app-aeb7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh8eEsdnGPmqLzF1EgB76i1n8CjZohv9w',
    appId: '1:398887128767:ios:c28141edf3bb3a1517000a',
    messagingSenderId: '398887128767',
    projectId: 'pet-app-aeb7b',
    storageBucket: 'pet-app-aeb7b.appspot.com',
    iosClientId: '398887128767-ng98fhbj89u2r0q2d40ga5agd448612e.apps.googleusercontent.com',
    iosBundleId: 'com.example.cronometroPet',
  );
}
